### ISSUE TITLE
Update to scala 2.11.1

### ISSUE THREAD

**Issue by amitsudharshan** [mattpap/IScala#7]
Is there any hope of an update to scala 2.11.1?
I played with updating the library dependencies, but after resolving everything, the compiler errors were too much for me to dive into with just  a cursory glance.
I'm happy to help if you have pieces that I could work on.

best

**Comment by mattpap** [comment]
I updated `master` with most recent dependencies and added `scala_2.11` branch with 2.11.2 support.  I didn't test this too much, but the basic stuff seem to work. What remains to do is to make `master` branch work with 2.10 and 2.11 simultaneously.

**Comment by amitsudharshan** [comment]
I've just downloaded and built the scala_2.11 branch. When running the console command I get the following error: Any thoughts?

thanks!

Exception in thread "RequestsEventLoop" java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (no such table: sessions)
        at org.sqlite.DB.newSQLException(DB.java:383)
        at org.sqlite.DB.newSQLException(DB.java:387)
        at org.sqlite.DB.throwex(DB.java:374)
        at org.sqlite.NativeDB.prepare(Native Method)
        at org.sqlite.DB.prepare(DB.java:123)
        at org.sqlite.PrepStmt.<init>(PrepStmt.java:42)
        at org.sqlite.Conn.prepareStatement(Conn.java:404)
        at org.sqlite.Conn.prepareStatement(Conn.java:399)
        at org.sqlite.Conn.prepareStatement(Conn.java:383)
        at org.sqlite.Conn.prepareStatement(Conn.java:395)

**Comment by mattpap** [comment]
Support for Scala 2.11 was added in https://github.com/mattpap/IScala/commit/698081db9781742a526083622adc72ec610acfd8 and simultaneous support for 2.10 and 2.11 in https://github.com/mattpap/IScala/commit/67a647cb243885f7e4a414de94132cfe82d2e1c5.

**Comment by lev112** [comment]
What is the right way to compile with scala 2.10?

I've tried to set `scalaVersion := "2.10.4"` in `Build.scala`, and it compiles,
but I see some strange behavior...

I try to import spark package, and in the console it works fine, 
but in the notebook I get an error:
`error: object spark is not a member of package org.apache`

Is it a bug or did I do something wrong?
(in IScala 0.1 the same code works fine)

**Comment by mattpap** [comment]
@lev112, I moved this discussion to #14.
